### ISSUE TITLE
Fix compatibility with dbt 0.20.0+

### ISSUE THREAD

**Issue by Aylr** [snowplow/dbt-snowplow-web#38]
### Describe the bug

This package is currently not compatible with the [current version of dbt](https://pypi.org/project/dbt/).

### Steps to reproduce

1. `pip install dbt` (note version 0.21.0)
2. Adjust `packages.yml` file as follows:
```
packages:
  - package: snowplow/snowplow_web
    version: 0.3.0
```
3. Install package with `dbt deps`
4. Note incompatibility.

### Expected results

I expect the package to install successfully.

### Actual results

`Version error for package dbt-labs/dbt_utils: Could not find a satisfactory version from options: ['=0.7.4', '>=0.6.0', '<0.7.0']`

### System information
**The contents of your `packages.yml` file:**

```
packages:
  - package: snowplow/snowplow_web
    version: 0.3.0
  - package: dbt-labs/dbt_utils
    version: 0.7.4
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.21.0
   latest version: 0.21.0

Up to date!

Plugins:
  - snowflake: 0.21.0
```

**The operating system you're using:**
macOS

**The output of `python --version`:**
Python 3.9.8

### Are you interested in contributing the fix?

I'm happy to contribute a fix with a little guidance!

**Comment by paulboocock** [comment]
Thanks for the report. We're aware of this, it was caused by a breaking change in dbt between 0.19.0 and 0.20.0. The current plan is for releases up to 0.4.0 to support pre 0.20.0 versions. This ensures that those running dbt 0.18.0 and 0.19.0 can use the package on all warehouses. 

Then from 0.5.0 we will only support 0.20.0+. 

The next release (due this week) is 0.4.0, then we will begin on 0.5.0 to make this package compatible with dbt 0.20.0+.

**Comment by Aylr** [comment]
Thanks @paulboocock for the roadmap insight. Please let me know how I can contribute to your efforts!
