### ISSUE TITLE
Improve quarantined sessions exclusion logic

### ISSUE THREAD

**Issue by bill-warner** [snowplow/dbt-snowplow-web#60]
### Issue
In the sessions lifecycle manifest table we exclude very long sessions here:
https://github.com/snowplow/dbt-snowplow-web/blob/b12e45d4cd298f330a4df399813a5645a9c95303/models/base/manifest/snowplow_web_base_sessions_lifecycle_manifest.sql#L36
Using `not in` is not the most performant option here.

### Solution
Update to use `not exists`

**Comment by emielver** [comment]
## Summary
After doing some research, I've found that the general online consensus is that we should be using `not exists` where we can instead of `not in`.  This is corroborated by my anecdotal speed tests using the two alternatives. There is however a difference in behaviour between the two, as outlined [here](https://sqlinthewild.co.za/index.php/2010/02/18/not-exists-vs-not-in/):
> The most important thing to note about NOT EXISTS and NOT IN is that, unlike EXISTS and IN,  they are not equivalent in all cases. Specifically, when NULLs are involved they will return different results. To be totally specific, when the subquery returns even one null, NOT IN will not match any rows. 
... 
Exists cannot return NULL. It’s checking solely for the presence or absence of a row in the subquery and, hence, it can only return true or false. Since it cannot return NULL, there’s no possibility of a single NULL resulting in the entire expression evaluating to UNKNOWN.
Hence, when the column in the subquery that’s used for comparison with the outer table can have nulls in it, consider carefully which of NOT EXISTS or NOT IN you want to use.

My understanding of this leads me to believe that `NOT EXISTS` will still give us the desired behaviour, but it would be great to get your thoughts on that @bill-warner. Let me know what you think and if you agree then I'm happy to implement `NOT EXISTS` in the model instead of using `NOT IN`.

## Postgres
Following the advice of [this post](https://explainextended.com/2009/09/16/not-in-vs-not-exists-vs-left-join-is-null-postgresql/), it seems like for PostGres the best is to either use `not exists` or to use a `left join`, either works out to be the same.

## Redshift
Looking at the query plan for the original version and the `not exists` version, it seems like the `not exists` version has a higher cost and therefore should take longer. That being said, actually running the query we see faster results (by a factor of 10) using `not exists`, and it seems the common consensus [online](https://stackoverflow.com/questions/173041/not-in-vs-not-exists) is that `not exists` should be more performant across databases.

## Snowflake
Same sentiment as above, execution time cut in half when using `not exists` (from ~1000ms to ~500ms)

## Bigquery
Same speed increase seen for BQ

**Comment by bill-warner** [comment]
Good stuff. Yeh I concur with your findings. Let's make this change :)
